# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 934c4619ec7791ed970893ea7746475b2b077ed2e79ff40327f6699130077cdb61ca3d4b40fa4c0d4ee9fac56aaaa550408d51921f44e4cc8f89172107f7b62c

test:
  secret_key_base: 2d59ce1ce8b2b371002cf4bea7ea8bd9c701f5314b9a66836a1ed5749135e29ccdcb003ac3e82c754daef0a1331296146621ec22fecf9ef25460948dd2622cb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
